export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

export TERM=linux

alias mccctl='/opt/mcc-board-cli/bin/mccctl.py'
alias fpgaver='/opt/mcc-board-cli/bin/fpgaver.py'
alias pllconf='/opt/mcc-board-cli/bin/pllconf.py'
alias timereset='/opt/mcc-board-cli/bin/timereset.py'

fpgaver

