#!/usr/bin/env python3

import sys
import mmap

# change here to set FPGA registers / parameters
uiodev = "/dev/uio0"
commit_hash_addr = 0
commit_date_addr = 1
build_time_addr = 2
build_date_addr = 3
#

regs = []

def open_uio(uio):
   global regs
   try:
      fid = open(uio, 'r+b', 0)
   except FileNotFoundError:
      # silent fails
      sys.exit(-1)

   regs = mmap.mmap(fid.fileno(), 0x10000)

def read_register(add) -> int:
   global regs
   return int.from_bytes(regs[add*4:(add*4)+4], byteorder='little')

open_uio(uiodev)

commit_hash_str = hex(read_register(commit_hash_addr))[2:]

commit_date_value = hex(read_register(commit_date_addr))[2:].zfill(8)
commit_date_str = ''.join((
   commit_date_value[0:2], 
   '.',
   commit_date_value[2:4],
   '.',
   commit_date_value[4:8]
))
 
build_date_value = hex(read_register(build_date_addr))[2:].zfill(8)
build_date_str = ''.join((
   build_date_value[6:8], 
   '.',
   build_date_value[4:6],
   '.',
   build_date_value[0:4]
))

build_time_value = hex(read_register(build_time_addr))[2:].zfill(8)
build_time_str = ''.join((
   build_time_value[0:2],
   ':',
   build_time_value[2:4],
   ':',
   build_time_value[4:6],
   '.',
   build_time_value[6:8],
))

print(f"\n# FPGA bitstream: build: {build_date_str}/{build_time_str}, commit: {commit_date_str}/{commit_hash_str}\n")
